# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Init Laravel
    init: |
      docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/opt -w /opt laravelsail/php82-composer:latest composer install --ignore-platform-reqs
    before: |
      cd monolith
      alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
    command: | 
      cd monolith
      sail up

  - name: Additional Laravel commands
    before: |
      cd monolith
      alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
    command: |
      sail artisan migrate

  - name: Init VueJS
    init: |
      echo Booting VueJS...
    command: |
      echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Application
    description: Port 80 for the application
    port: 80
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - mtxr.sqltools
    - ms-azuretools.vscode-docker