# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Init Laravel
    init: |
      echo Initializing Laravel...
    command: | 
      ./monolith/vendor/bin/sail up
  - name: Boot VueJS
    init: |
      echo Booting VueJS...
    command: |
      echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - mtxr.sqltools
    - ms-azuretools.vscode-docker